MVC5Restaurant/Controllers/Api/FoodsController.cs
using MVC5Restaurant.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace MVC5Restaurant.Controllers.Api
{
    public class FoodsController : ApiController
    {
        private ApplicationDbContext _context;

        public FoodsController()
        {
            _context = new ApplicationDbContext();
        }

        [System.Web.Http.HttpDelete]
        [System.Web.Mvc.Authorize(Roles = RoleName.CanManageFood)]
        public void DeleteFood(int id)
        {
            var foodInDb = _context.Foods.SingleOrDefault(f => f.Id == id);

            if (foodInDb == null)
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }
            else
            {
                //var foodController = DependencyResolver.Current.GetService<MVC5Restaurant.Controllers.FoodsController>();
                //foodController.UnsetFile(id);

                var fullPathToPhoto = System.Web.Hosting.HostingEnvironment.MapPath("~/Content/Images/" + foodInDb.File);

                if (System.IO.File.Exists(fullPathToPhoto))
                {
                    System.IO.File.Delete(fullPathToPhoto);
                }

                _context.Foods.Remove(foodInDb);
                _context.SaveChanges();
            }
        }
    }
}

MVC5Restaurant/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC5Restaurant.Models;
using System.Net.Mail;
using System.Text;
using System.Net;
using System.Threading.Tasks;

namespace MVC5Restaurant.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [Route("About")]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        //[Route("Contact")]
        //public ActionResult Contact()
        //{
        //    return View();
        //}

        public ActionResult Success()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Send(EmailSender e)
        {
            if(ModelState.IsValid)
            {
                var smtp = new SmtpClient();

                var body = "<p><b><u>Email From:</u></b> {0} ({1})</p><p><b><u>Message:</u></b></p><p>{2}</p>";
                var message = new MailMessage();
                message.To.Add(new MailAddress("angiesiudevworks@gmail.com"));
                message.From = new MailAddress(e.Email.ToString());
                message.Subject = "MVC5DessertCafe: " + e.Subject.ToString();
                message.Body = string.Format(body, e.Name, e.Email, e.Body);
                message.IsBodyHtml = true;

                await smtp.SendMailAsync(message);

                return RedirectToAction("Success");

            }
            return RedirectToAction("About", "Home");
            
        }
    }
}

MVC5Restaurant/Views/Home/About.cshtml
@model MVC5Restaurant.Models.EmailSender

@{
    ViewBag.Title = "About";
}
<h2 class="text-center">Welcome to the MVC5DessertCafe!</h2>

<div class="row">
    <p class="text-center">This is my demo ASP.NET MVC5 web project. If you like what you see, give me a shout!</p>
</div>

<div class="col-md-6">
    <h3>Give Us A Shout!</h3>
    <div class="col-md-12">
        @using (Html.BeginForm("Send", "Home"))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="form-group">
                @Html.LabelFor(model => model.Name)
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = "First Last" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Subject)
                @Html.TextBoxFor(model => model.Subject, new { @class = "form-control", placeholder = "Example: do you do parties?" })
                @Html.ValidationMessageFor(model => model.Subject)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Email, "Email Address:")
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control", placeholder = "youremail@example.com", type = "email" })
                @Html.ValidationMessageFor(model => model.Email)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Body, "Message:")
                @Html.TextAreaFor(model => model.Body, new { @class = "form-control", placeholder = "Your message here" })
                @Html.ValidationMessageFor(model => model.Body)
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit"><i class="fa fa-paper-plane"></i> Send!</button>
            </div>
        }
    </div>
</div>

<div class="col-md-6">
    <h3>Visit Us</h3>
    <div class="col-md-12">
        <p>MVC5DessertCafe</p>
        <p>73 Varick Street</p>
        <p>New York, NY 10013</p>
        <iframe id="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3023.793581138673!2d-74.00851098411835!3d40.72256037933077!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c2598b4a7f9733%3A0xd51bd44874c8bab2!2s73+Varick+St%2C+New+York%2C+NY+10013!5e0!3m2!1sen!2sus!4v1482181797204" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC5Restaurant/Views/Home/Contact.cshtml
@model MVC5Restaurant.Models.EmailSender

@{
    ViewBag.Title = "About";
}
<h2 class="text-center">Welcome to the MVC5DessertCafe!</h2>

<div class="row">
    <p class="text-center">This is my demo ASP.NET MVC5 web project. If you like what you see, give me a shout!</p>
</div>

<div class="col-md-6">
    <h3>Give Us A Shout!</h3>
    <div class="col-md-12">
        @using (Html.BeginForm("Send", "Home"))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="form-group">
                @Html.LabelFor(model => model.Name)
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Subject)
                @Html.TextBoxFor(model => model.Subject, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Subject)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Email, "Email Address:")
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Email)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Body, "Message:")
                @Html.TextAreaFor(model => model.Body, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Body)
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit"><i class="fa fa-paper-plane"></i> Send!</button>
                @*<button class="btn btn-default" type="reset">Reset</button>*@
            </div>
        }
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC5Restaurant/Views/Home/Index.cshtml
@{
    Layout = "";
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    ViewBag.Title = "Welcome!";
    @Styles.Render("~/Content/Home.css")
    @Styles.Render("~/Content/font-awesome.css")
    <link href='http://fonts.googleapis.com/css?family=Gochi+Hand' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Happy+Monkey' rel='stylesheet' type='text/css'>
}

<div class="fullscreen-bg">
    <video loop muted autoplay poster="~/Content/Images/baking_vid_still.PNG" class="fullscreen-bg__video">
        <source src="~/Content/Videos/baking.webm" type="video/webm">
        <source src="~/Content/Videos/baking.mp4" type="video/mp4">
        <source src="~/Content/Videos/baking.ogv" type="video/ogg">
    </video>
</div>

<div class="content-container">
    <div class="content">
        <h1>
            <i class="fa fa-cutlery"></i> MVC5DessertCafe
        </h1>
        <div class="enter-container">
            <a href="@Url.Action("Index", "Foods")">
                <h2>Enter</h2>
            </a>
        </div>
        <div class="legal-container">
            <p>Stock video background courtesy of <a href="https://videos.pexels.com/" target="_blank">Pexels Videos</a></p>
            <p>
                <b>&copy; Angie Siu</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://angiesiudevworks.com" target="_blank"><i class="fa fa-terminal"></i> angie siu dev works</a>
                <br />
                <em>All dessert images are property of Angie Siu.</em>
            </p>
        </div>
    </div>
</div>

MVC5Restaurant/Views/Home/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Got it! <i class="fa fa-smile-o"></i></h2>


<h4>Your message was sent to us successfully. We'll get back to you soon! We promise!</h4>
<br /><br /><br />
<h5 class="text-center">Redirecting to home page in:</h5>
<h2 id="count" class="text-center">5</h2>

@section scripts {

    <script>
        var $Countdown = $Countdown || {};

        $Countdown = function () {
            var props = {
                countFrom: 5,
                speed: 1000, //ms
                countText: $('#count')
            };

            var doCount = function () {
                setInterval(function () {
                    if (props.countFrom < 0) {
                        clearInterval(doCount);
                        window.location.href = '@Url.Action("Index", "Foods")';
                    } else {
                        setCountText();
                        props.countFrom--;
                    }
                }, props.speed);
            };

            var setCountText = function () {
                props.countText.html(props.countFrom);
            };

            this.init = function () {
                doCount();
            };
        };

        var countdown = new $Countdown();
        countdown.init();
    </script>
    
}